- name: Node repo key is present
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Node repo is added
  apt_repository:
    repo: "{{item}}"
    state: present
  with_items:
    - deb https://deb.nodesource.com/node_{{NODE_VERSION}}.x {{ansible_lsb.codename}} main
    - deb-src https://deb.nodesource.com/node_{{NODE_VERSION}}.x {{ansible_lsb.codename}} main
  register: node_repo_added

- name: Update apt-cache
  apt:
    update_cache: true
  when: node_repo_added.changed

- name: Node is installed
  apt:
    pkg: nodejs
    state: latest
    