- name: Deploy user exists
  user:
    name: "{{HARDEN_DEPLOY_USERNAME}}"
    append: true
    groups: sudo
    password: "{{ HARDEN_DEPLOY_PASSWORD|password_hash('sha512',HARDEN_DEPLOY_SALT)}}"
    state: present

- name: Deploy user accepts our pubkey
  authorized_key:
    key: "{{lookup('file','ssh_pubkey.pub')}}"
    user: "{{HARDEN_DEPLOY_USERNAME}}"
    state: present

- name: Update APT Cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Standard packages are installed
  apt: 
    state: installed
    pkg: "{{item}}"
  with_items: "{{HARDEN_PACKAGES}}"

- name: Ports are closed by default
  ufw:
    state: enabled
    policy: deny

- name: SSH port is open 
  ufw:
    rule: allow
    port: "{{SSH_PORT}}"

- name: Change SSH port
  lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: ^Port\s
    line: Port {{ SSH_PORT }}
    state: present
  notify: Restart SSH

- name: SSH root login is not permitted
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin
    line: PermitRootLogin no
    state: present
  notify: Restart SSH
  
- name: SSH password login is disabled
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^#?PasswordAuthentication
    line: PasswordAuthentication no
  notify: Restart SSH